name: Build an angular project
on:
  push:
    branches:
      - master
      - pipeline

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm i
      - name: Instal angular
        run: npm i -g @angular/cli
      - name: Build
        run: ng build --base-href ${{ secrets.BASE_HREF }} --configuration production
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist.${GITHUB_SHA::6}
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          name: deploy_dist
      - name: Build and deploy
        run: |
          sudo apt-get update
          sudo apt-get install sshpass -y
          npm install -g @angular/cli
          ng build --base-href ${{ secrets.BASE_HREF }} --configuration production
          sshpass -v -p '${{ secrets.SSH_PASS }}' scp -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/grbpwr.com/html
